@copy src\jvoipconfig.h include
@copy src\jvoiperrors.h include
@copy src\jvoipexception.h include
@copy src\jvoipsession.h include
@copy src\jvoipsessionparams.h include
@copy src\jvoipsigwait.h include
@copy src\jvoipthread.h include
@copy src\jvoiptypes.h include
@copy src\jvoipconfig_win.h include
@copy src\componentframework\location3d.h include
@copy src\componentframework\sampleinput.h include
@copy src\componentframework\sampleoutput.h include
@copy src\componentframework\samplingtimer.h include
@copy src\componentframework\transform3d.h include
@copy src\componentframework\voiceblock.h include
@copy src\componentframework\voicecall.h include
@copy src\componentframework\voicecompressor.h include
@copy src\componentframework\voicedecompressor.h include
@copy src\componentframework\voicemixer.h include
@copy src\componentframework\voicetransmitter.h include
@copy src\componentframework\voicetypes.h include
@copy src\libcomponents\base\jvoipcomponent.h include
@copy src\libcomponents\base\jvoipcomponentparams.h include
@copy src\libcomponents\base\jvoipcompression.h include
@copy src\libcomponents\base\jvoipcompressionmodule.h include
@copy src\libcomponents\base\jvoiplocalisation.h include
@copy src\libcomponents\base\jvoipmixer.h include
@copy src\libcomponents\base\jvoipsamplingtimer.h include
@copy src\libcomponents\base\jvoiptransmission.h include
@copy src\libcomponents\base\jvoipvoiceinput.h include
@copy src\libcomponents\base\jvoipvoiceoutput.h include
@copy src\libcomponents\base\jvoipsessionlocalisation.h include
@copy src\libcomponents\impl\jvoipnormalmixer.h include
@copy src\libcomponents\impl\jvoiprtptransmission.h include
@copy src\libcomponents\impl\jvoipsampleconverter.h include
@copy src\libcomponents\impl\jvoipsimpletimer.h include
@copy src\libcomponents\impl\win32\jvoipmixerstatus.h include
@copy src\libcomponents\impl\win32\jvoipsoundcardinput.h include
@copy src\libcomponents\impl\win32\jvoipsoundcardoutput.h include
@copy src\libcomponents\impl\jvoipsilencesuppression.h include
@copy src\libcomponents\impl\jvoipnoinput.h include
@copy src\libcomponents\impl\jvoipnooutput.h include
@copy src\libcomponents\impl\jvoipdpcmcompression.h include
@copy src\libcomponents\impl\jvoipsimplelocalisation.h include
@copy src\libcomponents\impl\jvoiphrtflocalisation.h include
@copy src\libcomponents\impl\jvoipgsmcompression.h include
@copy src\libcomponents\impl\jvoiplpccompression.h include
@copy src\libcomponents\impl\jvoipulawcompression.h include
@copy src\libcomponents\impl\jvoipspeexcompression.h include
@copy src\libcomponents\impl\jvoipfileinput.h include
@copy src\libcomponents\impl\jvoipfileoutput.h include
@copy src\debugnew.h include
@copy src\thirdparty\gsm\inc\gsm.h include
@copy src\thirdparty\lpc\lpccodec.h include
